[package]
name = "tree-sitter-camdl"
version = "0.0.1"
autoexamples = false
categories = ["parsing", "text-editors"]
edition = "2021"
keywords = ["incremental", "parsing", "tree-sitter", "camdl"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tree-sitter/tree-sitter-camdl"
description = "Camdl grammar for tree-sitter"

build = "bindings/rust/build.rs"
include = ["bindings/rust/*", "grammar.js", "queries/*", "src/*"]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = ">=0.22.6"

[build-dependencies]
cc = "1.0.87"
