//! Byte-identical FORWARD-trajectory baseline gate for the corner-case fixtures —
//! the off-grid / coincident / fractional / lifecycle stress models the on-grid
//! golden corpus lacks (`tests/fixtures/corner_cases/`, see its README). Sibling
//! to `gate_trajectory_baseline.rs`, which walks the on-grid `ocaml/golden`
//! corpus; this one pins the forward trajectories of the paths the
//! unified-timeline refactor's merged `Schedule` actually changes: the off-grid
//! intervention snap, the coincident-boundary order, the fractional output end,
//! and the full substep lifecycle (events + intervention + balance).
//!
//! At `Simulate::run` ALL model interventions fire (it resolves `fire_steps` for
//! everything; the CLI's default-off is a CLI-layer filter), so these models
//! exercise the intervention/event/balance boundary handling without `--enable`.
//!
//! The IR under `tests/fixtures/corner_cases/ir/*.ir.json` is compiled from the
//! `.camdl` with params baked via `camdlc --set` (regenerated by
//! `make update-corner-golden`). Baselines are machine/toolchain-specific (libm)
//! — a development ratchet, same caveat as `gate_trajectory_baseline.rs`.
//! Re-capture with
//!   CAMDL_CAPTURE_BASELINE=1 cargo test -p sim --test gate_corner_case_baseline -- --nocapture
//! and paste the printed table into BASELINES.

use std::path::PathBuf;

use sim::{
    compiled_model::CompiledModel,
    config::{ChainBinomialConfig, GillespieConfig, OdeConfig, SimConfig},
    simulate::Simulate,
    ChainBinomialSim, GillespieSim, OdeSim,
};

const SEED: u64 = 42;

fn ir_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../tests/fixtures/corner_cases/ir")
}

fn discover_models() -> Vec<String> {
    let dir = ir_dir();
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {:?}: {}", dir, e))
        .filter_map(|entry| {
            let name = entry.ok()?.file_name().into_string().ok()?;
            name.strip_suffix(".ir.json").map(|s| s.to_owned())
        })
        .collect();
    names.sort();
    names
}

fn load(name: &str) -> ir::Model {
    let path = ir_dir().join(format!("{}.ir.json", name));
    let contents = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("could not read {:?}: {}", path, e));
    ir::from_str(&contents).unwrap_or_else(|e| panic!("failed to parse {}: {}", name, e))
}

/// FNV-1a/64 over the full trajectory numeric content — identical to
/// `gate_trajectory_baseline.rs` so the two gates are comparable.
fn trajectory_hash(traj: &sim::state::Trajectory) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    let mut mix = |bytes: &[u8]| {
        for &b in bytes {
            h ^= b as u64;
            h = h.wrapping_mul(0x100000001b3);
        }
    };
    for snap in &traj.snapshots {
        mix(&snap.t.to_bits().to_le_bytes());
        for &c in &snap.int_state.counts {
            mix(&c.to_le_bytes());
        }
        for &v in &snap.real_state.values {
            mix(&v.to_bits().to_le_bytes());
        }
    }
    h
}

/// Committed baselines: (model, backend) -> trajectory hash, captured on the dev
/// machine. Re-capture with CAMDL_CAPTURE_BASELINE=1 (see the module header).
const BASELINES: &[(&str, &str, u64)] = &[
    ("all_lifecycle", "chain_binomial", 0xaad69690736b2061),
    ("coincident_obs_intervention", "gillespie", 0xc95855be016faa2e),
    ("coincident_obs_intervention", "chain_binomial", 0x268779bebe644754),
    ("coincident_obs_intervention", "ode", 0x8e4f3e32f11b6c80), // ODE de-quant (exact fraction-transfer)
    // event_drain_fusion (cycle 2a): a live transition DRAINS A every substep
    // while an always_active value-dependent event (transfer fraction=f of A)
    // ALSO reads A. The event delta floor(A*f) is read from the START-OF-STEP
    // SNAPSHOT (pre-drain A), fused atomically with the transition delta. ode
    // (RK4) and gillespie (SSA) have distinct kernels and get their own pinned
    // baselines.
    ("event_drain_fusion", "gillespie", 0xa793914cfeab7c40),
    ("event_drain_fusion", "chain_binomial", 0x9f09ba4bd868112c),
    // ode moved with the effect-purity seam's ODE de-quantization: a
    // fraction_transfer on integer compartments now applies the exact fraction
    // of the f64 integrator state (src*frac) instead of floor(round(src)*frac).
    // The recurring every-step leak compounds the fractional carry. Verified
    // exact by effects::tests::continuous_fraction_transfer_is_exact; discrete
    // backends byte-identical.
    ("event_drain_fusion", "ode", 0xf6cc6cd7b95392ac),
    // event_intervention_agree: a coincident always_active event + intervention
    // where the intervention reads the compartment the event modified. The
    // canonical (M1) lifecycle makes chain_binomial / ode byte-identical (same
    // hash); gillespie differs only in its absorbing-state output cadence, not
    // the terminal state. The cross-backend AGREEMENT on the terminal counts is
    // asserted directly in cross_backend_lifecycle_agreement.rs.
    ("event_intervention_agree", "gillespie", 0x178b6b9b28a16bca),
    ("event_intervention_agree", "chain_binomial", 0x17be41f06b7e1f78),
    ("event_intervention_agree", "ode", 0x17be41f06b7e1f78),
    ("fractional_output_end", "gillespie", 0x12ea70a5ebfd6189),
    ("fractional_output_end", "chain_binomial", 0x28067d22b8adc1b3),
    ("fractional_output_end", "ode", 0x55b55839abd925b5),
    ("off_grid_intervention", "gillespie", 0xe967c235c5278b90),
    ("off_grid_intervention", "chain_binomial", 0x4f96d41fadd2c78a),
    ("off_grid_intervention", "ode", 0x0bad82f510c7fca4), // ODE de-quant (exact fraction-transfer)
    ("off_grid_obs", "gillespie", 0x3a47fe1458a43c93),
    ("off_grid_obs", "chain_binomial", 0x38f9706bf047cf25),
    ("off_grid_obs", "ode", 0xfb342768c44ea834),
    // dt_rate: an `(dt/tau)`-scaled infection rate (`Expr::Dt`, gh#54). The
    // FORWARD backends never clip to obs times, so every substep is the full
    // grid dt=1 and the dt/tau factor is identically 1.0 (tau=1) — hence these
    // hashes EQUAL off_grid_obs above (same SIR otherwise). The dt-factor only
    // bites under Exact substep clipping, where dt_actual ≠ grid_dt; that path
    // is pinned by gate_dt_rate_exact_clip.rs, not here. (On gillespie/ode the
    // `Expr::Dt` node freezes to sim.dt-or-1.0 — deterministic but degenerate;
    // dt-rates are only meaningful on the fixed-step / inference path.)
    ("dt_rate", "gillespie", 0x3a47fe1458a43c93),
    ("dt_rate", "chain_binomial", 0x38f9706bf047cf25),
    ("dt_rate", "ode", 0xfb342768c44ea834),
    // seasonal_drift runs here at dt=1 (integer), where s*dt == accumulated, so
    // these pin the integer-dt behaviour.
    ("seasonal_drift", "gillespie", 0x3ebeed379edb8107),
    ("seasonal_drift", "chain_binomial", 0xf8db0999aa8fe812),
    ("seasonal_drift", "ode", 0x631a6bb7eba02031),
];

#[test]
fn corner_case_trajectory_baselines_hold() {
    let capture = std::env::var("CAMDL_CAPTURE_BASELINE").is_ok();
    let mut captured: Vec<String> = Vec::new();
    let mut missing: Vec<String> = Vec::new();

    for name in discover_models() {
        let model = load(&name);
        let compiled =
            CompiledModel::new(model).unwrap_or_else(|e| panic!("compile {}: {:?}", name, e));
        let params = compiled.default_params.clone();
        let t_start = compiled.model.simulation.t_start;
        let t_end = compiled.model.simulation.t_end;

        let backends: &[(&str, SimConfig)] = &[
            ("gillespie", SimConfig::Gillespie(GillespieConfig { t_start, t_end, output_dt: None })),
            ("chain_binomial", SimConfig::ChainBinomial(ChainBinomialConfig { t_start, t_end, dt: 1.0 })),
            ("ode", SimConfig::Ode(OdeConfig { t_start, t_end, dt: 1.0 })),
        ];
        let required = compiled.required_capabilities();

        for (backend, config) in backends {
            let sim: &dyn Simulate = match *backend {
                "gillespie" => &GillespieSim,
                "ode" => &OdeSim,
                _ => &ChainBinomialSim,
            };
            // Capability-skip: e.g. balance (all_lifecycle) is chain-binomial only.
            if !(required - sim.capabilities()).is_empty() {
                continue;
            }
            let traj = match sim.run(&compiled, &params, SEED, config) {
                Ok(t) => t,
                Err(_) => continue, // baseline-time sim errors are not this gate's concern
            };
            let hash = trajectory_hash(&traj);
            if capture {
                captured.push(format!("    (\"{name}\", \"{backend}\", 0x{hash:016x}),"));
                continue;
            }
            match BASELINES.iter().find(|(n, b, _)| *n == name && *b == *backend).map(|(_, _, h)| *h) {
                Some(expected) => assert_eq!(
                    hash, expected,
                    "TRAJECTORY CHANGED for {name}/{backend}: a refactor perturbed the \
                     forward trajectory (got 0x{hash:016x}, expected 0x{expected:016x})"
                ),
                None => missing.push(format!("{name}/{backend}")),
            }
        }
    }

    if capture {
        eprintln!("\n// <<CAPTURED-BASELINES>> — paste into BASELINES:");
        for line in &captured {
            eprintln!("{line}");
        }
        return;
    }
    assert!(
        missing.is_empty(),
        "no baseline for: {missing:?} — run with CAMDL_CAPTURE_BASELINE=1 and paste the table"
    );
}
