//! gh#166 Phase B (proposal gates #1, #2): external incidence/prevalence oracle.
//!
//! The augmented ODE flow (Q1B) moves every ODE golden's incidence. This gate is
//! the proof that the NEW flows are *more correct*, not merely different: camdl's
//! fixed-RK4 ODE backend is compared, at the output grid, against three
//! INDEPENDENT adaptive integrators — scipy `solve_ivp` (RK45 and LSODA) and R
//! `deSolve::lsoda` — for BOTH prevalence (compartment levels) and incidence
//! (per-interval transition flows). The references are cached TSVs under
//! `tests/external/ode_oracle/ref/` (regenerated by `gen/run.sh`); CI reads only
//! the cache and needs neither Python nor R.
//!
//! Each reference solves the SAME canonical RHS augmented with one
//! cumulative-incidence variable per transition (`dc_i/dt = rate_i`) — exactly
//! the construct camdl's augmented flow implements — so agreement validates the
//! augmented mechanism end to end, including the sub-unit slow-transition regime
//! (TB reactivation). The model params are baked into `models/*.ir.json` and the
//! generators by hand; if they ever drift, the trajectories diverge and this gate
//! fails (it is self-checking against param drift).

use sim::{
    compiled_model::CompiledModel,
    config::{OdeConfig, SimConfig},
    simulate::Simulate,
    OdeSim,
};

const SEED: u64 = 0;

fn oracle_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../tests/external/ode_oracle"
    ))
}

struct OracleModel {
    name: &'static str,
    comps: &'static [&'static str],
    incs: &'static [&'static str],
    t_end: f64,
    /// Fixed RK4 substep — fine enough that RK4 truncation is far below the
    /// tolerances; the output grid stays daily (step 1.0).
    dt: f64,
}

/// One row of a reference TSV: prevalence per compartment, per-interval
/// incidence per transition, indexed in the model's declared order.
struct RefRow {
    t: f64,
    prev: Vec<f64>,
    inc: Vec<f64>,
}

fn load_ref(path: &std::path::Path, ncomp: usize, ninc: usize) -> Vec<RefRow> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read reference {:?}: {e}", path));
    let mut rows = Vec::new();
    for (li, line) in text.lines().enumerate() {
        if li == 0 {
            continue; // header
        }
        let f: Vec<f64> = line
            .split('\t')
            .map(|s| s.trim().parse::<f64>().unwrap_or_else(|_| panic!("parse {:?} in {:?}", s, path)))
            .collect();
        assert_eq!(
            f.len(),
            1 + ncomp + ninc,
            "reference {:?} row {li} has {} cols, expected {}",
            path, f.len(), 1 + ncomp + ninc
        );
        rows.push(RefRow {
            t: f[0],
            prev: f[1..1 + ncomp].to_vec(),
            inc: f[1 + ncomp..1 + ncomp + ninc].to_vec(),
        });
    }
    rows
}

fn oracle_models() -> [OracleModel; 3] {
    [
        OracleModel { name: "sir", comps: &["S", "I", "R"], incs: &["infection", "recovery"], t_end: 60.0, dt: 0.1 },
        OracleModel { name: "seir", comps: &["S", "E", "I", "R"], incs: &["infection", "progression", "recovery"], t_end: 80.0, dt: 0.1 },
        OracleModel {
            name: "tb",
            comps: &["S", "Lf", "Ls", "I", "R"],
            incs: &["infection", "fast_prog", "stabilize", "reactivate", "recovery"],
            t_end: 365.0,
            dt: 0.1,
        },
    ]
}

/// Compile the named oracle model, optionally switching it to rk45 with the given
/// `(atol, rtol)`. `None` → the default fixed RK4.
fn compiled_model(name: &str, rk45: Option<(f64, f64)>) -> CompiledModel {
    let path = oracle_dir().join("models").join(format!("{name}.ir.json"));
    let json = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {:?}: {e}", path));
    let mut model = ir::from_str(&json).unwrap_or_else(|e| panic!("parse {name}: {e}"));
    if let Some((atol, rtol)) = rk45 {
        model.simulation.integrator = ir::model::Integrator::Rk45 { atol: Some(atol), rtol: Some(rtol) };
    }
    CompiledModel::new(model).unwrap_or_else(|e| panic!("compile {name}: {e}"))
}

// Combined absolute+relative tolerances, |camdl - ref| <= atol + rtol*|ref|.
// Prevalence: camdl reports integer compartment counts ROUNDED at snapshot
// (±0.5), so atol=1.0 absorbs rounding; rtol catches integration drift.
// Incidence: camdl's flow is unrounded real, so it tracks the oracle tightly even
// at sub-unit magnitudes — atol guards the floor, rtol the bulk.
const PREV_ATOL: f64 = 1.0;
const PREV_RTOL: f64 = 1e-3;
const INC_ATOL: f64 = 1e-2;
const INC_RTOL: f64 = 1e-3;

/// Compare a camdl trajectory against the three cached references (scipy RK45,
/// scipy LSODA, R deSolve::lsoda) for both prevalence and incidence at the grid.
fn check_against_oracle(traj: &sim::state::Trajectory, m: &OracleModel, label: &str) {
    for method in ["scipy_rk45", "scipy_lsoda", "desolve_lsoda"] {
        let ref_path = oracle_dir().join("ref").join(format!("{}__{}.tsv", m.name, method));
        let refrows = load_ref(&ref_path, m.comps.len(), m.incs.len());
        let (mut worst_prev, mut worst_inc) = (0.0_f64, 0.0_f64);
        for rr in &refrows {
            let snap = traj
                .snapshots
                .iter()
                .find(|s| (s.t - rr.t).abs() < 1e-9)
                .unwrap_or_else(|| panic!("{} [{label}]: no camdl snapshot at t={}", m.name, rr.t));
            let flows = snap.flows.as_real();
            for c in 0..m.comps.len() {
                let got = snap.int_state.counts[c] as f64;
                let want = rr.prev[c];
                let tol = PREV_ATOL + PREV_RTOL * want.abs();
                let d = (got - want).abs();
                worst_prev = worst_prev.max(d / tol);
                assert!(
                    d <= tol,
                    "{}/{} [{label}]: prevalence {} at t={} : camdl {} vs oracle {} (Δ {:.4e} > tol {:.4e})",
                    m.name, method, m.comps[c], rr.t, got, want, d, tol
                );
            }
            for i in 0..m.incs.len() {
                let got = flows[i];
                let want = rr.inc[i];
                let tol = INC_ATOL + INC_RTOL * want.abs();
                let d = (got - want).abs();
                worst_inc = worst_inc.max(d / tol);
                assert!(
                    d <= tol,
                    "{}/{} [{label}]: incidence {} over (t-1,{}] : camdl {} vs oracle {} (Δ {:.4e} > tol {:.4e})",
                    m.name, method, m.incs[i], rr.t, got, want, d, tol
                );
            }
        }
        eprintln!(
            "{}/{} [{label}]: OK ({} grid pts; worst prev {:.1}% of tol, worst inc {:.1}% of tol)",
            m.name, method, refrows.len(), 100.0 * worst_prev, 100.0 * worst_inc
        );
    }
}

#[test]
fn ode_incidence_matches_scipy_and_desolve() {
    for m in &oracle_models() {
        let compiled = compiled_model(m.name, None);
        assert!(
            !compiled.required_capabilities().contains(sim::Capabilities::RUNTIME_DT),
            "{}: oracle models must use the augmented flow path",
            m.name
        );
        let params = compiled.default_params.clone();
        let cfg = SimConfig::Ode(OdeConfig { t_start: 0.0, t_end: m.t_end, dt: m.dt });
        let traj = OdeSim.run(&compiled, &params, SEED, &cfg).expect("ode run");
        check_against_oracle(&traj, m, "rk4");
    }
}

/// gh#166 C6: the adaptive rk45 integrator validated DIRECTLY against scipy
/// `solve_ivp` (RK45 — the same DOPRI5 algorithm) + LSODA and R deSolve, for both
/// prevalence and incidence. rk45's initial-step guess is the nominal `dt`; the
/// controller adapts, so the comparison is integrator-internals-agnostic.
#[test]
fn ode_rk45_incidence_matches_scipy_and_desolve() {
    for m in &oracle_models() {
        let compiled = compiled_model(m.name, Some((1e-10, 1e-10)));
        let params = compiled.default_params.clone();
        let cfg = SimConfig::Ode(OdeConfig { t_start: 0.0, t_end: m.t_end, dt: 1.0 });
        let traj = OdeSim.run(&compiled, &params, SEED, &cfg).expect("rk45 ode run");
        check_against_oracle(&traj, m, "rk45");
    }
}
