#!/usr/bin/env python3
"""Generate parametric toy SEIR spatial+age .camdl models for scaling benches.

The toy model faithfully reproduces the force-of-infection (FOI) *shape* of the
real Kano measles model (`playpen-camdl-measles/.../kano_lga_seirv.camdl`): the
per-patch aggregates `N[l]`, `I_agg[l]` and the spatial coupling **sum inside the
infection rate** — `kappa * sum(q in patch, W[l,q]*I_agg[q]/N[q])`. That sum is
what the OCaml compiler flat-inlines into every `(patch,age)` infection rate tree
(and into each free parameter's gradient tree), producing the observed IR blowup.

Knobs (the experimental axes):
  P         number of patches (spatial units) — the dominant O(P^2) axis
  A         number of age groups
  coupling  'on'  → include the kappa*sum(q...) spatial term  (O(P) per infection)
            'off' → drop it (control: isolates the spatial term as the O(P^2) source)
  grad      'full'    → FOI params (R0,gamma,kappa,amplitude,iota) are FREE params,
                        so camdlc emits a rate_grad tree per param (IR-size multiplier)
            'minimal' → those constants are baked as literals, no free params,
                        no rate_grad (isolates the bare rate-tree cost)

Note: rate_grad is only consumed by gradient-based inference (PGAS/NUTS). Forward
`simulate` evaluates only `rate`, so the `grad` knob inflates IR/compile/parse/RSS
but NOT forward-sim stepping. That separation is intentional and measured.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _patch_names(P: int) -> list[str]:
    return [f"p{i}" for i in range(P)]


def _age_names(A: int) -> list[str]:
    return [f"a{i}" for i in range(A)]


def _w_matrix(P: int) -> str:
    """Row-normalised off-diagonal coupling: W[i][j] = 1/(P-1) for i!=j, 0 on diag.

    For P==1 there is no coupling target; callers should use coupling='off'.
    """
    if P == 1:
        return "[[0.0]]"
    off = round(1.0 / (P - 1), 8)
    rows = []
    for i in range(P):
        vals = [("0.0" if j == i else str(off)) for j in range(P)]
        rows.append("[" + ", ".join(vals) + "]")
    indent = ",\n" + " " * 24
    return "[" + indent.join(rows) + "]"


def _w_matrix_sparse(P: int, k: int) -> str:
    """Sparse ring coupling: patch i couples only to its k nearest neighbours
    (k//2 each side, wrapping), row-normalised over those k; 0 elsewhere.

    The realistic national-scale shape (local neighbour mixing) — a literal W
    with P*k nonzeros and P^2 - P*k structural zeros. The dense P-term FOI
    Reduce the expander emits collapses to a k-term Reduce once the
    constant-fold pass resolves the zero W cells and drops them.
    """
    half = max(1, k // 2)
    rows = []
    for i in range(P):
        nbrs = set()
        for d in range(1, half + 1):
            nbrs.add((i - d) % P)
            nbrs.add((i + d) % P)
        nbrs.discard(i)
        w = round(1.0 / len(nbrs), 8) if nbrs else 0.0
        vals = [(str(w) if j in nbrs else "0.0") for j in range(P)]
        rows.append("[" + ", ".join(vals) + "]")
    indent = ",\n" + " " * 24
    return "[" + indent.join(rows) + "]"


def gen_camdl(P: int, A: int, coupling: str, grad: str, observe: bool = False,
              coupling_degree: int = 0) -> str:
    assert coupling in ("on", "off")
    assert grad in ("full", "minimal")
    if coupling == "on" and P < 2:
        raise ValueError("coupling='on' requires P >= 2")

    patches = _patch_names(P)
    ages = _age_names(A)
    full = grad == "full"

    L: list[str] = []
    L.append(f"# Auto-generated scaling toy model: P={P} A={A} "
             f"coupling={coupling} grad={grad}")
    L.append("# Generated by scripts/gen_scaling_models.py — do not edit by hand.")
    L.append("time_unit = 'days")
    L.append("")
    L.append("compartments { S, E, I, R }")
    L.append("")
    L.append("dimensions {")
    L.append(f"  patch = [{', '.join(patches)}]")
    L.append(f"  age   = [{', '.join(ages)}]")
    L.append("}")
    L.append("")
    L.append("stratify(by = patch)")
    L.append("stratify(by = age)")
    L.append("")
    # Per-patch aggregates — the big PopSum trees (O(A) and O(C*A)).
    L.append("let N[l in patch]     = sum(a in age, S[l, a] + E[l, a] + I[l, a] + R[l, a])")
    L.append("let I_agg[l in patch] = sum(a in age, I[l, a])")
    L.append("")

    # Parameters / constants depending on grad knob.
    if full:
        L.append("parameters {")
        L.append("  R0        : positive    in [5.0, 30.0]")
        L.append("  sigma     : rate        in [0.05, 0.30]")
        L.append("  gamma     : rate        in [0.05, 0.30]")
        if coupling == "on":
            L.append("  kappa     : probability in [0.0, 1.0]")
        L.append("  amplitude : probability in [0.0, 0.7]")
        L.append("  iota      : positive    in [1e-10, 1e-3]")
        L.append("}")
        L.append("")
        L.append("let beta = R0 * gamma")
        L.append("let seas = 1.0 - amplitude + amplitude * 2.0 * school(t)")
        iota_term = "iota"
        kappa_term = "kappa"
        sigma_rate = "sigma"
        gamma_rate = "gamma"
    else:
        # Everything baked to literals: zero free params → no rate_grad.
        L.append("let beta = 2.145")              # ~ R0=15 * gamma=0.143
        L.append("let seas = 0.75 + 0.5 * school(t)")  # amplitude=0.25 baked
        iota_term = "0.0000001"
        kappa_term = "0.05"
        sigma_rate = "0.125"
        gamma_rate = "0.143"

    L.append("")
    L.append("forcing {")
    L.append("  school : periodic 'ratio {")
    L.append("    period = 365.25 'days")
    L.append("    step   = 1 'days")
    L.append("    on     = [0:182]")
    L.append("  }")
    L.append("}")
    L.append("")

    if coupling == "on":
        w_lit = _w_matrix_sparse(P, coupling_degree) if coupling_degree > 0 else _w_matrix(P)
        L.append("tables {")
        L.append(f"  W : patch × patch = {w_lit}")
        L.append("}")
        L.append("")

    # ── Transitions ──────────────────────────────────────────────────────────
    L.append("transitions {")
    foi_local = f"(I_agg[l] + {iota_term}) / N[l]"
    if coupling == "on":
        if coupling_degree > 0:
            # Guarded form: W[l,q] * (if N[q] > 0 then I_agg[q]/N[q] else 0).
            # Makes the constant-fold sound — a zero-W term folds 0*(finite)->0
            # in one step (the division lives inside the guard, never reached
            # when the term is zeroed), so dropping it is byte-identical.
            inner = "(if N[q] > 0 then I_agg[q] / N[q] else 0.0)"
        else:
            inner = "I_agg[q] / N[q]"
        foi_spatial = (f"\n      + {kappa_term} * "
                       f"sum(q in patch, W[l, q] * {inner})")
    else:
        foi_spatial = ""
    L.append("  infection[l in patch, a in age] : S[l, a] --> E[l, a]")
    L.append(f"    @ beta * seas * S[l, a] * (")
    L.append(f"        {foi_local}{foi_spatial}")
    L.append("      )")
    L.append("")
    L.append(f"  progression[l in patch, a in age] : E[l, a] --> I[l, a] @ {sigma_rate} * E[l, a]")
    L.append(f"  recovery[l in patch, a in age]    : I[l, a] --> R[l, a] @ {gamma_rate} * I[l, a]")
    L.append("}")
    L.append("")

    # Observation model (opt-in via --observe) — a single weekly stream over
    # *total* infectious prevalence. Bare `I` sums over all strata (spec §11
    # "bare = sum over ALL strata"); we use `prevalence(I)` rather than
    # `incidence(infection)` because the latter currently fails to resolve a
    # base (pre-expansion) transition name in a stratified model (E507). For
    # inference *profiling* the observable is irrelevant — the particle filter
    # steps the full model regardless. Literal reporting params (rho=0.5, NB
    # dispersion r=5) keep scaling benches byte-identical without --observe;
    # PMMH/PGAS estimate the existing free FOI params (R0, gamma, …).
    if observe:
        L.append("observations {")
        L.append("  weekly_cases : {")
        L.append("    projected  = prevalence(I)")
        L.append("    every      = 7 'days")
        L.append("    likelihood = neg_binomial(mean = 0.5 * projected, r = 5.0)")
        L.append("  }")
        L.append("}")
        L.append("")

    # ── Init (all positive so every source group is active → full eval cost) ──
    L.append("init {")
    L.append("  S[l in patch, a in age] = 900")
    L.append("  E[l in patch, a in age] = 10")
    L.append("  I[l in patch, a in age] = 10")
    L.append("  R[l in patch, a in age] = 80")
    L.append("}")
    L.append("")
    L.append("simulate {")
    L.append("  from = 0 'days")
    L.append("  to   = 365 'days")
    L.append("}")
    L.append("")

    # Scenario only needed when there are free params to pin.
    if full:
        L.append("scenarios {")
        L.append("  baseline {")
        L.append('    label = "scaling toy baseline"')
        L.append("    set = {")
        L.append("      R0        = 15.0")
        L.append("      sigma     = 0.125")
        L.append("      gamma     = 0.143")
        if coupling == "on":
            L.append("      kappa     = 0.05")
        L.append("      amplitude = 0.25")
        L.append("      iota      = 1e-7")
        L.append("    }")
        L.append("  }")
        L.append("}")
        L.append("")

    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--patches", "-P", type=int, required=True)
    ap.add_argument("--ages", "-A", type=int, required=True)
    ap.add_argument("--coupling", choices=("on", "off"), default="on")
    ap.add_argument("--grad", choices=("full", "minimal"), default="full")
    ap.add_argument("--observe", action="store_true",
                    help="add a weekly_cases observation block (for PMMH/PGAS "
                         "inference profiling); off by default so scaling "
                         "benches stay byte-identical")
    ap.add_argument("--coupling-degree", type=int, default=0, metavar="K",
                    help="sparse ring coupling: each patch couples to its K "
                         "nearest neighbours (rest of W = 0) + a guarded FOI; "
                         "0 (default) = dense all-to-all W (the FOI-blowup shape)")
    ap.add_argument("-o", "--out", type=Path, default=None,
                    help="output .camdl path (default: stdout)")
    args = ap.parse_args()

    text = gen_camdl(args.patches, args.ages, args.coupling, args.grad, args.observe,
                     coupling_degree=args.coupling_degree)
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text)
        print(f"wrote {args.out} ({len(text)} bytes)", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
